#hash([build-stamp . ""]
      [catalogs . ("https://download.racket-lang.org/releases/8.2/catalog/" #f)]
      [doc-search-url . "https://download.racket-lang.org/releases/8.2/doc/local-redirect/index.html"]
      [apps-dir . "/tmp/racket-issue-3969/layer/share/applications"]
      [config-tethered-console-bin-dir . "/tmp/racket-issue-3969/layer/bin"]
      [config-tethered-gui-bin-dir . "/tmp/racket-issue-3969/layer/bin"]
      [bin-dir . "/tmp/racket-issue-3969/layer/bin"]
      [bin-search-dirs . (#f "/tmp/racket-issue-3969/racket/bin")]
      [lib-dir . "/tmp/racket-issue-3969/layer/lib/racket"]
      [lib-search-dirs . (#f "/tmp/racket-issue-3969/racket/lib")]
      [share-dir . "/tmp/racket-issue-3969/layer/share/racket"]
      [share-search-dirs . (#f "/tmp/racket-issue-3969/racket/share")]
      [links-file . "/tmp/racket-issue-3969/layer/share/racket/links.rktd"]
      [links-search-files . (#f "/tmp/racket-issue-3969/racket/share/links.rktd")]
      [pkgs-dir . "/tmp/racket-issue-3969/layer/share/racket/pkgs"]
      [pkgs-search-dirs . (#f "/tmp/racket-issue-3969/racket/share/pkgs")]
      [man-dir . "/tmp/racket-issue-3969/layer/share/man"]
      [man-search-dirs . (#f "/tmp/racket-issue-3969/racket/man")]
      [doc-dir . "/tmp/racket-issue-3969/layer/share/doc/racket"]
      [doc-search-dirs . (#f "/tmp/racket-issue-3969/racket/doc")]
      [include-dir . "/tmp/racket-issue-3969/layer/include/racket"]
      [include-search-dirs . (#f "/tmp/racket-issue-3969/racket/include")])
